### ISSUE TITLE
cannot

### ISSUE THREAD

**Issue by LinKolnLee** [jegumhon/URWeatherView#1]
<img width="650" alt="2017-06-30 10 41 53" src="https://user-images.githubusercontent.com/24311526/27718793-c7fdabea-5d80-11e7-901d-6523dd7a8288.png">

**Comment by Urtaq** [comment]
Do you use Cocoapods? If so, you need to follow the instructions on README like below.
Because the example project is for the carthage...
<img width="733" alt="2017-06-30 2 58 47" src="https://user-images.githubusercontent.com/6110163/27722817-bc925034-5da4-11e7-91e7-2e3cdd053d00.png">
